name: Sync JetBrains Releases

on:
  schedule:
    # 每两天执行一次 (UTC时间)
    - cron: "0 0 */2 * *"
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 PyGithub
        
    - name: Run sync script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python jetbrains_sync.py \
          --product-url "https://www.jetbrains.com/idea/download/other.html" \
          --repo "${{ github.repository }}" \
          --github-token "${{ secrets.GITHUB_TOKEN }}"
          
    - name: Commit changes (if any)
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .
        git commit -m "Update release metadata" || true
        git push
