name: 同步JetBrains版本

on:
  schedule:
    # 每两天运行一次 (UTC时间)
    - cron: '0 0 */2 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: 检出仓库
      uses: actions/checkout@v4
      with:
        # 必须设置fetch-depth为0以获取完整历史记录
        fetch-depth: 0
      
    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 PyGithub requests
        
    - name: 同步IntelliJ IDEA
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PRODUCT_URL: "https://www.jetbrains.com/idea/download/other.html"
      run: python sync_jetbrains.py
      
